// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Navatala Systems (OPC) Pvt Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer buf_alpha {
  float alpha[];
};
layout(std430, binding = 1) readonly buffer buf_phi {
  float phi[];
};
layout(std430, binding = 2) readonly buffer buf_owner {
  int owner[];
};
layout(std430, binding = 3) readonly buffer buf_nei {
  int nei[];
};
layout(std430, binding = 4) readonly buffer buf_gradX {
  float gradX[];
};
layout(std430, binding = 5) readonly buffer buf_gradY {
  float gradY[];
};
layout(std430, binding = 6) readonly buffer buf_gradZ {
  float gradZ[];
};
layout(std430, binding = 7) readonly buffer buf_cellCx {
  float cellCx[];
};
layout(std430, binding = 8) readonly buffer buf_cellCy {
  float cellCy[];
};
layout(std430, binding = 9) readonly buffer buf_cellCz {
  float cellCz[];
};
layout(std430, binding = 10) readonly buffer buf_weights {
  float weights[];
};
layout(std430, binding = 11) readonly buffer buf_phir {
  float phir[];
};
layout(std430, binding = 12) readonly buffer buf_alphaF {
  float alphaF[];
};
layout(std430, binding = 13) readonly buffer buf_faceParams {
  int faceParams[];
};
layout(std430, binding = 14) writeonly buffer buf_outAlphaPhi {
  float outAlphaPhi[];
};

// kernel: navatala_cfd_vof_alpha_phi_van_leer_int
void main() {
  int gid0 = int(gl_GlobalInvocationID.x);
  if (int(int(gl_GlobalInvocationID.x)) >= faceParams[0]) {
    return;
  } else {
    float ph = phi[int(int(gl_GlobalInvocationID.x))];
    int o = owner[int(int(gl_GlobalInvocationID.x))];
    int n = nei[int(int(gl_GlobalInvocationID.x))];
    float aO = alpha[o];
    float aN = alpha[n];
    float gradf = (aN - aO);
    float gxU = gradX[n];
    float gyU = gradY[n];
    float gzU = gradZ[n];
    if (ph > uintBitsToFloat(0x00000000u)) {
      gxU = gradX[o];
      gyU = gradY[o];
      gzU = gradZ[o];
    }
    float dx = (cellCx[n] - cellCx[o]);
    float dy = (cellCy[n] - cellCy[o]);
    float dz = (cellCz[n] - cellCz[o]);
    float gradcf = (((dx * gxU) + (dy * gyU)) + (dz * gzU));
    float absGradf = abs(gradf);
    float absGradcf = abs(gradcf);
    float gradfSign = uintBitsToFloat(0x3f800000u);
    if (gradf < uintBitsToFloat(0x00000000u)) {
      gradfSign = uintBitsToFloat(0xbf800000u);
    }
    float gradcfSign = uintBitsToFloat(0x3f800000u);
    if (gradcf < uintBitsToFloat(0x00000000u)) {
      gradcfSign = uintBitsToFloat(0xbf800000u);
    }
    float r = uintBitsToFloat(0x00000000u);
    if (absGradf > uintBitsToFloat(0x0da24260u)) {
      if (absGradcf >= (uintBitsToFloat(0x447a0000u) * absGradf)) {
        r = ((uintBitsToFloat(0x44fa0000u) * (gradcfSign * gradfSign)) - uintBitsToFloat(0x3f800000u));
      } else {
        r = ((uintBitsToFloat(0x40000000u) * (gradcf / gradf)) - uintBitsToFloat(0x3f800000u));
      }
    }
    float absR = abs(r);
    float psi = ((r + absR) / (uintBitsToFloat(0x3f800000u) + absR));
    if (((ph > uintBitsToFloat(0x00000000u)) && ((aO < uintBitsToFloat(0x00000000u)) || (aN > uintBitsToFloat(0x3f800000u)))) || ((ph < uintBitsToFloat(0x00000000u)) && ((aN < uintBitsToFloat(0x00000000u)) || (aO > uintBitsToFloat(0x3f800000u))))) {
      psi = uintBitsToFloat(0x00000000u);
    }
    float pos0 = uintBitsToFloat(0x00000000u);
    if (ph >= uintBitsToFloat(0x00000000u)) {
      pos0 = uintBitsToFloat(0x3f800000u);
    }
    float cdw = weights[int(int(gl_GlobalInvocationID.x))];
    float w = ((psi * cdw) + ((uintBitsToFloat(0x3f800000u) - psi) * pos0));
    float oneMinusW = (uintBitsToFloat(0x3f800000u) - w);
    float a = ((w * aO) + (oneMinusW * aN));
    float ac = alphaF[int(int(gl_GlobalInvocationID.x))];
    if (ac < uintBitsToFloat(0x00000000u)) {
      ac = uintBitsToFloat(0x00000000u);
    }
    if (ac > uintBitsToFloat(0x3f800000u)) {
      ac = uintBitsToFloat(0x3f800000u);
    }
    float oneMinusAc = (uintBitsToFloat(0x3f800000u) - ac);
    float comp = (ac * oneMinusAc);
    outAlphaPhi[int(int(gl_GlobalInvocationID.x))] = ((ph * a) + (phir[int(int(gl_GlobalInvocationID.x))] * comp));
  }
}
