# The same registered controls run in-tree and against an immutable release library.
add_executable(test_unavailable_ffi "${CMAKE_CURRENT_LIST_DIR}/test_unavailable_ffi.cpp")
set(_ffi_controls test_unavailable_ffi)
if(NOT GPU_RUNTIME_NAVATALA_FFI_STUB)
    add_executable(test_unsupported_neural_ffi "${CMAKE_CURRENT_LIST_DIR}/test_unsupported_neural_ffi.cpp")
    list(APPEND _ffi_controls test_unsupported_neural_ffi)
endif()
foreach(control IN LISTS _ffi_controls)
    target_link_libraries(${control} PRIVATE gpu_runtime)
    target_include_directories(${control} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../include")
    target_compile_features(${control} PRIVATE cxx_std_17)
endforeach()
if(GPU_RUNTIME_NAVATALA_FFI_STUB)
    set(_ffi_control_mode stub)
else()
    set(_ffi_control_mode real)
endif()
add_test(NAME NavatalaUnavailableFfi COMMAND test_unavailable_ffi "${_ffi_control_mode}")
set_tests_properties(NavatalaUnavailableFfi PROPERTIES SKIP_RETURN_CODE 77)
if(NOT GPU_RUNTIME_NAVATALA_FFI_STUB)
    add_test(NAME NavatalaUnsupportedNeuralFfi COMMAND test_unsupported_neural_ffi)
endif()
