# Shared by the private runtime and the public projection's CMake overlay.
set(GPU_RUNTIME_PROFILE "GENERAL" CACHE STRING "Runtime profile: GENERAL or SEALED_EXACT")
set_property(CACHE GPU_RUNTIME_PROFILE PROPERTY STRINGS GENERAL SEALED_EXACT)
set(GPU_RUNTIME_REQUIRED_BACKENDS "" CACHE STRING "Exact backend set required by SEALED_EXACT")
option(GPU_RUNTIME_ENABLE_NVRTC "Enable CUDA source JIT compilation" ON)

if(NOT GPU_RUNTIME_PROFILE STREQUAL "GENERAL" AND
   NOT GPU_RUNTIME_PROFILE STREQUAL "SEALED_EXACT")
    message(FATAL_ERROR "Unknown GPU_RUNTIME_PROFILE: ${GPU_RUNTIME_PROFILE}")
endif()

if(GPU_RUNTIME_PROFILE STREQUAL "SEALED_EXACT")
    if(GPU_RUNTIME_NAVATALA_FFI_STUB OR NOT GPU_RUNTIME_NAVATALA_WRAPPER)
        message(FATAL_ERROR "SEALED_EXACT requires the real Navatala FFI and wrapper")
    endif()
    if(GPU_RUNTIME_ENABLE_NVRTC)
        message(FATAL_ERROR "SEALED_EXACT requires GPU_RUNTIME_ENABLE_NVRTC=OFF")
    endif()
    if("${GPU_RUNTIME_REQUIRED_BACKENDS}" STREQUAL "")
        message(FATAL_ERROR "SEALED_EXACT requires an explicit nonempty backend set")
    endif()
endif()

function(gpu_runtime_validate_backend_profile)
    set(known CUDA HIP METAL VULKAN OPENCL)
    set(compiled "")
    foreach(backend IN LISTS known)
        if(GPU_RUNTIME_HAVE_${backend})
            list(APPEND compiled "${backend}")
        endif()
    endforeach()
    list(SORT compiled)
    if(GPU_RUNTIME_PROFILE STREQUAL "SEALED_EXACT")
        set(required "${GPU_RUNTIME_REQUIRED_BACKENDS}")
        foreach(backend IN LISTS required)
            if(NOT backend IN_LIST known)
                message(FATAL_ERROR "Unknown required backend: ${backend}")
            endif()
        endforeach()
        list(LENGTH required original_count)
        list(REMOVE_DUPLICATES required)
        list(LENGTH required unique_count)
        if(NOT original_count EQUAL unique_count)
            message(FATAL_ERROR "Duplicate required backend")
        endif()
        list(SORT required)
        foreach(backend IN LISTS known)
            if(GPU_RUNTIME_USE_${backend} AND NOT backend IN_LIST required)
                message(FATAL_ERROR "Unrequested backend enabled: ${backend}")
            endif()
        endforeach()
        if(NOT "${compiled}" STREQUAL "${required}")
            message(FATAL_ERROR "Required backend set '${required}' differs from compiled set '${compiled}'")
        endif()
    endif()
    set(GPU_RUNTIME_COMPILED_BACKENDS "${compiled}" CACHE INTERNAL "Observed compiled backend set" FORCE)
endfunction()
