// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Navatala Systems (OPC) Pvt Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer buf_dstIdx {
  uint dstIdx[];
};
layout(std430, binding = 1) readonly buffer buf_messages {
  float messages[];
};
layout(std430, binding = 2) readonly buffer buf_detN {
  int detN[];
};
layout(std430, binding = 3) writeonly buffer buf_keys_scatter_0 {
  uint keys_scatter_0[];
};
layout(std430, binding = 4) writeonly buffer buf_vals_scatter_0 {
  float vals_scatter_0[];
};

// kernel: navatala_samples_det_prepare_scatter_0
void main() {
  int gid0 = int(gl_GlobalInvocationID.x);
  if (int(gl_GlobalInvocationID.x) < detN[0]) {
    keys_scatter_0[int(gl_GlobalInvocationID.x)] = dstIdx[int(gl_GlobalInvocationID.x)];
    vals_scatter_0[int(gl_GlobalInvocationID.x)] = messages[int(gl_GlobalInvocationID.x)];
  }
}
